DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS blogs;

CREATE TABLE blogs (
	id SERIAL PRIMARY KEY,
	title VARCHAR(100) NOT NULL,
	content TEXT NOT NULL,
	created_at TIMESTAMP NOT null DEFAULT NOW(),
	updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE comments (
	id SERIAL PRIMARY KEY,
	blog_id INT NOT NULL,
	content TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
	CONSTRAINT fk_blog FOREIGN KEY(blog_id) 
		REFERENCES blogs(id) ON DELETE CASCADE
);
